### ISSUE TITLE
curl command not found for coreos

### ISSUE THREAD

**Issue by sonamsamdupkhangsar** [5pi/infra#25]
Hi there,

I plugged-in your driver into my k8s cluster on digital ocean using CoreOS.  The script runs but then it complains the curl command is not found.  I wonder if it's run within a container where the curl is not installed.  After installing curl, libcurl is not found.  Any hints on how to install curl and libcurl lib?

thanks

**Comment by discordianfish** [comment]
This isn't using coreos. Not sure where you got that from. You need to first build your image in packer/.
